### ISSUE TITLE
Expose services through reverse proxy

### ISSUE THREAD

**Issue by vsapronov** [syncloud/insider#7]
Services could be exposed through reverse proxy instead of drilling ports for each service independently. This will require automation of nginx configuration for reverse proxy and adding services behind it.

Benefits are:
1. One port (or two ports for http and https) to watch for could be easier.
2. The one port could be port 80 (or 80 and 443 for https) which is enabling urls without ports: boris.syncloud.it/owncloud.

Bad sides:
Performance could be worse with one more service running on the board.

**Comment by cyberb** [comment]
Fixed by server/apache apps + insider local port preference.
